# Global variables
# SETTINGS
CAN_SWING_ONTO_FRIENDLY_TOKEN = 1
BFS_DEBUG = 0
SINGLE_TOKEN_SHOW_ROUTE = 1
GET_CHILD_STATES_DEBUG = 1
CHILD_STATES_SHOW_HEX = 1

# Maximum distance from the centre hex
BOARD_SIZE = 4
UPPER_SIGN = "()"
LOWER_SIGN = "  "
BLOCK_SIGN = "#####"
